<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="52" started-at="2019-10-30T17:15:12Z" finished-at="2019-10-30T17:15:12Z">
    <groups>
      <group name="smoke">
        <method signature="FirstDemo.div()[pri:0, instance:test.FirstDemo@4e04a765]" name="div" class="test.FirstDemo"/>
        <method signature="FirstDemo.mul()[pri:0, instance:test.FirstDemo@4e04a765]" name="mul" class="test.FirstDemo"/>
        <method signature="FirstDemo.sub()[pri:0, instance:test.FirstDemo@4e04a765]" name="sub" class="test.FirstDemo"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="FirstDemo.div()[pri:0, instance:test.FirstDemo@4e04a765]" name="div" class="test.FirstDemo"/>
        <method signature="FirstDemo.mul()[pri:0, instance:test.FirstDemo@4e04a765]" name="mul" class="test.FirstDemo"/>
        <method signature="FirstDemo.sub()[pri:0, instance:test.FirstDemo@4e04a765]" name="sub" class="test.FirstDemo"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Test" duration-ms="52" started-at="2019-10-30T17:15:12Z" finished-at="2019-10-30T17:15:12Z">
      <class name="test.FirstDemo">
        <test-method status="PASS" signature="div()[pri:0, instance:test.FirstDemo@4e04a765]" name="div" duration-ms="12" started-at="2019-10-30T17:15:12Z" finished-at="2019-10-30T17:15:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- div -->
        <test-method status="PASS" signature="mul()[pri:0, instance:test.FirstDemo@4e04a765]" name="mul" duration-ms="1" started-at="2019-10-30T17:15:12Z" finished-at="2019-10-30T17:15:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mul -->
        <test-method status="FAIL" signature="sub()[pri:0, instance:test.FirstDemo@4e04a765]" name="sub" duration-ms="1" started-at="2019-10-30T17:15:12Z" finished-at="2019-10-30T17:15:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [10] but found [20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [10] but found [20]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at test.FirstDemo.sub(FirstDemo.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sub -->
      </class> <!-- test.FirstDemo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
